name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - uses: actions/checkout@v3

    # 2. Cài Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Cài dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Chạy unittest trực tiếp
    - name: Run tests
      run: python -m unittest discover -s tests -p "*.py" -v
